blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/oakensoul/claude-personal-assistant/discussions
    about: Ask questions, share ideas, and discuss AIDA with the community
  - name: 📖 Documentation
    url: https://github.com/oakensoul/claude-personal-assistant/tree/main/docs
    about: Read the AIDA documentation
