name: 🔴 Defect Report
description: Report a bug in released/production code
labels: ["type:defect", "priority:p1"]
body:
  - type: markdown
    attributes:
      value: |
        ## Defect Report

        Report bugs in **released/production code** that affect users.

        For issues in **unreleased/development code**, use the **Bug Report** template instead.

        ⚠️ Defects are automatically marked as **P1 (High Priority)** since they affect released code.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Override default P1 if needed
      options:
        - P1 (High - default for defects)
        - P0 (Critical - production down, data loss)
        - P2 (Medium - workaround available)
        - P3 (Low - cosmetic issue)
      default: 0

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the defect
      placeholder: What's broken in production?
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: User Impact
      description: How does this affect users?
      placeholder: |
        - Who is affected?
        - How many users?
        - What can't they do?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this defect?
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Affected Version
      description: Which version(s) have this defect?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Is there a temporary workaround?
      placeholder: Users can work around this by...

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this fix will be?
      options:
        - Unknown
        - XS (1-2 hours)
        - S (2-4 hours)
        - M (1-2 days)
        - L (3-5 days)
        - XL (1-2 weeks)
      default: 0

  - type: textarea
    id: agents
    attributes:
      label: Suggested Agents
      description: Which development agents should work on this?
      placeholder: |
        @shell-script-specialist
        @qa-engineer
        @privacy-security-auditor
