name: Lint

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

# Prevent duplicate workflow runs on PR pushes
# - PR pushes: Share group using head_ref (only latest run completes)
# - Branch pushes: Unique group per branch using ref_name
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint All Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for gitleaks

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure
